Openshift: Add License and metadata for public release
Add the license, notice, and metadata tags needed for public release

Change-Id: I107dae6f5a8dc188a92f54b919cc38b3dc4983be
Signed-off-by: VijayaRamarao Mellempudi <quic_vmellemp@quicinc.com>
Signed-off-by: Carl Streeter <quic_carls@quicinc.com>

diff --git a/manual_install/src_img_build/qcom-src-img-Dockerfile b/manual_install/src_img_build/qcom-src-img-Dockerfile
--- a/manual_install/src_img_build/qcom-src-img-Dockerfile
+++ b/manual_install/src_img_build/qcom-src-img-Dockerfile
@@ -1,3 +1,19 @@
 FROM registry.access.redhat.com/ubi9/ubi-micro:9.4
 ARG SRC_ROOT_DIR
 COPY ${SRC_ROOT_DIR} /
+
+# Include license and location information
+LABEL org.opencontainers.image.source https://github.com/quic/cloud-ai-containers
+COPY --chmod=755 motd.sh /etc
+COPY CONTAINER_LICENSE.txt /usr/share/doc
+RUN ln -s /usr/share/doc/CONTAINER_LICENSE.txt / && \
+    ln -s /usr/share/doc/CONTAINER_LICENSE.txt /root && \
+# Different systems use different system wide non-login shell config files
+    if [ -e /etc/bash.bashrc ]; then \
+        echo '[ ! -z "$TERM" -a -r /etc/motd.sh ] && /etc/motd.sh' >> /etc/bash.bashrc ; \
+    elif [ -e /etc/bashrc ]; then \
+        echo '[ ! -z "$TERM" -a -r /etc/motd.sh ] && /etc/motd.sh' >> /etc/bashrc ; \
+    else \
+        echo "Unable to find system bashrc" ; \
+        exit 1 ; \
+    fi
